#!/bin/sh

# These changes take effect immediately and persist across logins.

gsettings set org.gnome.desktop.input-sources xkb-options \
  "['caps:ctrl_modifier', 'shift:both_capslock']"
gsettings set org.gnome.desktop.interface gtk-key-theme "Emacs"
gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true
