#!/bin/sh

set -e
PATH="/usr/local/bin:$PATH"
git_dir="`git rev-parse --git-dir`"        # repo's git dir
top_dir="`git rev-parse --show-toplevel`"  # repo's root dir
trap 'rm -rf "$git_dir/$$.gtags"' EXIT     # delete temp directory upon EXIT

mkdir -p "$git_dir/$$.gtags"

# pipe project's files to gtags
# write to temp directory <pid>.gtags
git ls-files | \
  gtags --file - "$git_dir/$$.gtags"

mv "$git_dir/$$.gtags/"{GTAGS,GRTAGS,GPATH} "$top_dir"  # files: GTAGS GRTAGS GPATH

