#!/bin/sh

set -e
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags"' EXIT

# write to temp file .git/<pid>.tags
hasktags \
    --ctags \
    --extendedctag \
    --tags-absolute \
    --output "$dir/$$.tags" \
    .

mv "$dir/$$.tags" "$dir/tags"  # tagfile: .git/tags
